name: "pearson_test"

services:
  # Webserver (nginx)
  pearson_test_webserver:
    image: nginx
    container_name: pearson_test_webserver
    working_dir: /var/www/html
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
      - ./code:/var/www/html
    ports:
      - "80:80"

  # Backend service (php8.3)
  pearson_test_backend:
    image: ahmedmgad/php:8.3-xdebug
    hostname: pearson_test_backend
    user: "root:root"
    container_name: pearson_test_backend
    working_dir: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./code:/var/www/html
    command: [ "/bin/bash","-c","php-fpm -y /usr/local/etc/php-fpm.conf -R" ]